const divElement = document.getElementById('myDiv');
divElement.style.backgroundColor = 'yellow';
divElement.style.margin = '20px';
divElement.style.padding = '10px';
divElement.style.fontSize = '18px';
divElement.style.fontWeight = 'bold';
divElement.style.height = '200px';
divElement.style.width = '300px';
divElement.style.color = 'blue';
